package com.hbnu.common;

public enum MsgType {
    SERVER_ERROR,
//    登录请求
    LOGIN_REQUEST,
    LOGIN_SUCCESSFUL,
    LOGIN_FAILED,
//    异地登录
    LOGIN_OUT,
//    获取密保
    SECURITY_QUESTIONS_REQUEST,
    SECURITY_QUESTIONS_SUCCESSFUL,
    SECURITY_QUESTIONS_FAILED,
//    校验密保获取密码
    GET_BACK_REQUEST,
    GET_BACK_SUCCESSFUL,
    GET_BACK_FAILED,
//    获取用户名
    GET_USERNAME_REQUEST,
    GET_USERNAME_SUCCESSFUL,
    GET_USERNAME_FAILED,
//    注册请求
    REGISTRATION_REQUEST,
    REGISTRATION_SUCCESSFUL,
    REGISTRATION_FAILED,
//    获取好友，群组，自己昵称头像
    GET_DATA_LIST,
    GET_DATA_LIST_SUCCESSFUL,
    GET_ONLINE_LIST,
    GET_ONLINE_LIST_SUCCESSFUL,
//    获取历史聊天信息
    GET_MESSAGE,
//    创建群聊
    CREATE_GROUP,
//    加入群聊
    ADD_GROUP,
//    发送私聊消息
    SEND_MESSAGE_PRIVATE,
//    发送群组消息
    SEND_MESSAGE_GROUP,
//    查看所有用户
    VIEW_USERS,
//    查找用户
    SELECT_USER_REQUEST,
    SELECT_USER_SUCCESSFUL,
    SELECT_USER_FALIED,
//    修改用户信息
    UPDATE_USER_REQUEST,
    UPDATE_USER_SUCCESSFUL,
    GET_USER_INFO_REQUEST,
    GET_USER_INFO_SUCCESSFUL,
//    添加好友
    ADD_USER_REQUEST,
    ADD_USER_SUCCESSFUL,
//    注销账号
    DELETE_USER_REQUEST,
//    账号登出
    LOGOUT_REQUEST,
    LOGOUT_SUCCESSFUL,
}
